package com.example.demo.Model.Request;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;


@Data
@AllArgsConstructor
@NoArgsConstructor
public class ChatGptRequest implements Serializable {

    private String model;    //The model is a machine learning model. In this example, I am using the popular model called text-davinci-002. This model is used to predict data
    private String prompt; //instruction
    private Double temperature; // The temperature parameter in GPT-3 is a hyperparameter that controls the randomness or creativity of the model’s outputs.
    @JsonProperty("max_tokens")
    private Integer maxTokens; //This is used to specify the max number of tokens generated by the model.
    @JsonProperty("top_p")
    private Double topP; //The top p parameter specifies a sampling threshold during inference time. It is actually another way to control the randomness and creativity of the text.


}


//ChatGptRequest, is a more complex request object used to
// make requests to the OpenAI GPT-3 natural language processing API.

// BotRequest may be passed as the prompt to ChatGptRequest to generate a response from the GPT-3 model.