package com.example.demo.Model.response;

import lombok.Data;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.List;

@Data

public class ChatGptResponse implements Serializable {
    private String id; // ID of the request
    private String object;
    private String model;
    private LocalDate created; // the date and time the response was generated.
    private List<choice> choices;  //a list of responses generated by the GPT-3 model
}
