package com.example.demo.Model.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.io.Serializable;

@Data
public class choice implements Serializable {
    private Integer index;  //the order of the choice in the list of responses
    private String text; //actual text generated by the model

    @JsonProperty("finish_reason") // annotation used to specify the name of the JSON property

    private String finishReason; // information about why the model stopped generating text
}
